name: UKM Workflow

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Current directory files
        run: ls
      - name: NPM Install
        run: 'npm install'
      - name: Run ng lint
        run: 'npm run lint'

