name: UKM Workflow

on: [push]

jobs:
  update-release-draft:
    name: "Update Release Draft"
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.6.1
        with:
          config-name: workflows/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-test-build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Make All Scripts Executable
        run: chmod +x ./scripts/*
      - name: Setup Fake Firebase Config
        run: ./scripts/setup-fake-firebase-config.sh
      - name: Test Firestore Rules
        run: npm run test-firestore-rules
      - name: Test with Headless Chrome
        run: npm run test-headless
      - name: Build
        run: npm run build
